import type { CategoryColorTokenValue, CategoryIconValue } from '@ghar/contracts'
import {
  ArrowLeftRight as ArrowLeftRightIcon,
  Baby as BabyIcon,
  Banknote as BanknoteIcon,
  BedDouble as BedDoubleIcon,
  Bike as BikeIcon,
  Briefcase as BriefcaseIcon,
  BriefcaseBusiness as BriefcaseBusinessIcon,
  Car as CarIcon,
  CarFront as CarFrontIcon,
  CarTaxiFront as CarTaxiFrontIcon,
  CircleEllipsis as CircleEllipsisIcon,
  CirclePlus as CirclePlusIcon,
  Coffee as CoffeeIcon,
  CreditCard as CreditCardIcon,
  Dumbbell as DumbbellIcon,
  Fuel as FuelIcon,
  Gamepad2 as Gamepad2Icon,
  Gift as GiftIcon,
  GraduationCap as GraduationCapIcon,
  Hammer as HammerIcon,
  HandCoins as HandCoinsIcon,
  HandHeart as HandHeartIcon,
  HeartPulse as HeartPulseIcon,
  House as HouseIcon,
  Key as KeyIcon,
  KeyRound as KeyRoundIcon,
  Landmark as LandmarkIcon,
  MonitorSmartphone as MonitorSmartphoneIcon,
  Package as PackageIcon,
  PartyPopper as PartyPopperIcon,
  PawPrint as PawPrintIcon,
  Percent as PercentIcon,
  PiggyBank as PiggyBankIcon,
  Pill as PillIcon,
  Plane as PlaneIcon,
  PlaneTakeoff as PlaneTakeoffIcon,
  PlugZap as PlugZapIcon,
  Receipt as ReceiptIcon,
  Scissors as ScissorsIcon,
  Shield as ShieldIcon,
  Shirt as ShirtIcon,
  ShoppingBag as ShoppingBagIcon,
  ShoppingCart as ShoppingCartIcon,
  Sofa as SofaIcon,
  SquareParking as SquareParkingIcon,
  Stethoscope as StethoscopeIcon,
  Tag as TagIcon,
  Ticket as TicketIcon,
  TrainFront as TrainFrontIcon,
  Tv as TvIcon,
  Undo2 as Undo2Icon,
  Users as UsersIcon,
  Utensils as UtensilsIcon,
  UtensilsCrossed as UtensilsCrossedIcon,
  Wallet as WalletIcon,
  Wifi as WifiIcon,
  Wine as WineIcon,
  Wrench as WrenchIcon,
  type LucideIcon,
} from 'lucide-react'
import { cn } from '@/lib/utils'

// Every icon a category may wear, by the name it is stored under. The names come from
// CATEGORY_ICONS in @ghar/core/finances and a contracts test keeps that list and the schema
// equal, so a missing entry here is a type error rather than a blank square on the screen.

export const CATEGORY_ICON_COMPONENTS: Record<CategoryIconValue, LucideIcon> = {
  'arrow-left-right': ArrowLeftRightIcon,
  'baby': BabyIcon,
  'banknote': BanknoteIcon,
  'bed-double': BedDoubleIcon,
  'bike': BikeIcon,
  'briefcase': BriefcaseIcon,
  'briefcase-business': BriefcaseBusinessIcon,
  'car': CarIcon,
  'car-front': CarFrontIcon,
  'car-taxi-front': CarTaxiFrontIcon,
  'circle-ellipsis': CircleEllipsisIcon,
  'circle-plus': CirclePlusIcon,
  'coffee': CoffeeIcon,
  'credit-card': CreditCardIcon,
  'dumbbell': DumbbellIcon,
  'fuel': FuelIcon,
  'gamepad-2': Gamepad2Icon,
  'gift': GiftIcon,
  'graduation-cap': GraduationCapIcon,
  'hammer': HammerIcon,
  'hand-coins': HandCoinsIcon,
  'hand-heart': HandHeartIcon,
  'heart-pulse': HeartPulseIcon,
  'house': HouseIcon,
  'key': KeyIcon,
  'key-round': KeyRoundIcon,
  'landmark': LandmarkIcon,
  'monitor-smartphone': MonitorSmartphoneIcon,
  'package': PackageIcon,
  'party-popper': PartyPopperIcon,
  'paw-print': PawPrintIcon,
  'percent': PercentIcon,
  'piggy-bank': PiggyBankIcon,
  'pill': PillIcon,
  'plane': PlaneIcon,
  'plane-takeoff': PlaneTakeoffIcon,
  'plug-zap': PlugZapIcon,
  'receipt': ReceiptIcon,
  'scissors': ScissorsIcon,
  'shield': ShieldIcon,
  'shirt': ShirtIcon,
  'shopping-bag': ShoppingBagIcon,
  'shopping-cart': ShoppingCartIcon,
  'sofa': SofaIcon,
  'square-parking': SquareParkingIcon,
  'stethoscope': StethoscopeIcon,
  'tag': TagIcon,
  'ticket': TicketIcon,
  'train-front': TrainFrontIcon,
  'tv': TvIcon,
  'undo-2': Undo2Icon,
  'users': UsersIcon,
  'utensils': UtensilsIcon,
  'utensils-crossed': UtensilsCrossedIcon,
  'wallet': WalletIcon,
  'wifi': WifiIcon,
  'wine': WineIcon,
  'wrench': WrenchIcon,
}

/** The tokens a category may be tinted with. Never a hex value; these come from packages/tokens. */
export const CATEGORY_COLOR_CLASSES = {
  ink: 'text-ink',
  'ink-muted': 'text-ink-muted',
  positive: 'text-positive',
  caution: 'text-caution-ink',
  negative: 'text-negative',
} as const satisfies Record<CategoryColorTokenValue, string>

/** A category's icon in its colour. Decorative: the category's name is always beside it. */
export function CategoryIcon({
  icon,
  colorToken,
  className,
}: {
  icon: CategoryIconValue
  colorToken: CategoryColorTokenValue
  className?: string
}) {
  const Icon = CATEGORY_ICON_COMPONENTS[icon]
  return <Icon aria-hidden className={cn('size-5 shrink-0', CATEGORY_COLOR_CLASSES[colorToken], className)} />
}
